// =====================================================================
// PRICES :: BUILDINGS   (classname -> value)
// STRUCTURES : price + build time (seconds).  DEFENSES : price only.
// =====================================================================

//--- Base/Base_West.sqf: STRUCTURE prices (9) ---
CTI_PRICES_STRUCTURES_WEST = createHashMapFromArray [
	["Land_Cargo_House_V1_F", 1000],
	["Land_i_Garage_V1_F", 2000],
	["Land_i_House_Small_03_V1_F", 3000],
	["Land_Cargo_HQ_V1_F", 3500],
	["Land_Radar_Small_F", 8000],
	["Land_TBox_F", 500],
	["Land_FuelStation_Build_F", 600],
	["Land_Lighthouse_small_F", 1500],
	["Land_TTowerBig_1_F", 8000]
];

//--- Base/Base_West.sqf: STRUCTURE build times (9) ---
CTI_PRICES_STRUCT_TIMES_WEST = createHashMapFromArray [
	["Land_Cargo_House_V1_F", 60],
	["Land_i_Garage_V1_F", 80],
	["Land_i_House_Small_03_V1_F", 90],
	["Land_Cargo_HQ_V1_F", 120],
	["Land_Radar_Small_F", 140],
	["Land_TBox_F", 40],
	["Land_FuelStation_Build_F", 35],
	["Land_Lighthouse_small_F", 35],
	["Land_TTowerBig_1_F", 120]
];

//--- Base/Base_West.sqf: DEFENSE prices (65) ---
CTI_PRICES_DEFENSES_WEST = createHashMapFromArray [
	["B_G_HMG_02_F", 150],
	["B_G_HMG_02_high_F", 150],
	["B_HMG_01_High_F", 200],
	["B_GMG_01_high_F", 350],
	["B_static_AT_F", 900],
	["B_static_AA_F", 800],
	["B_Mortar_01_F", 10000],
	["B_AAA_System_01_F", 25000],
	["B_SAM_System_01_F", 40000],
	["B_Radar_System_01_F", 20000],
	["B_SAM_System_03_F", 50000],
	["Land_LampHalogen_F", 5],
	["B_supplyCrate_F", 7],
	["Land_BagBunker_Small_F", 15],
	["Land_Dome_Small_F", 1500],
	["Land_Dome_Big_F", 6000],
	["Land_Cargo_Patrol_V1_F", 50],
	["Land_Shed_Big_F", 40],
	["Land_Cargo_Tower_V1_F", 5000],
	["Land_Mil_WallBig_4m_F", 20],
	["Land_CncWall4_F", 20],
	["Land_Mil_WiredFence_F", 5],
	["Land_HBarrier_5_F", 20],
	["Land_HBarrierBig_F", 20],
	["Land_HBarrierWall6_F", 40],
	["Land_HBarrierWall_corridor_F", 20],
	["Land_HBarrierTower_F", 40],
	["Land_CncBarrier_stripes_F", 15],
	["Land_Medevac_house_V1_F", 3000],
	["CamoNet_BLUFOR_F", 50],
	["CamoNet_BLUFOR_open_F", 50],
	["CamoNet_BLUFOR_big_F", 50],
	["Land_DragonsTeeth_01_1x1_new_F", 40],
	["Land_CzechHedgehog_01_new_F", 40],
	["Land_ConcreteHedgehog_01_F", 40],
	["Flag_NATO_F", 10],
	["Land_BagFence_Long_F", 5],
	["Land_BagFence_Short_F", 5],
	["Land_BagFence_Round_F", 5],
	["Land_Shed_Small_F", 200],
	["Land_Mil_WiredFence_Gate_F", 5],
	["Land_HelipadSquare_F", 10],
	["Land_Obstacle_Ramp_F", 1],
	["MapBoard_altis_F", 1],
	["Land_i_Shed_Ind_F", 2000],
	["Land_TentHangar_V1_F", 1000],
	["Land_Hangar_F", 2500],
	["Land_LightHouse_F", 2000],
	["Land_i_Barracks_V2_F", 3000],
	["Land_Flush_Light_green_F", 1],
	["Land_Flush_Light_red_F", 1],
	["Land_Flush_Light_yellow_F", 1],
	["Land_runway_edgelight_blue_F", 1],
	["Land_runway_edgelight", 1],
	["Land_Runway_PAPI", 1],
	["Land_Runway_PAPI_2", 1],
	["Land_Runway_PAPI_3", 1],
	["Land_Runway_PAPI_4", 1],
	["Land_Razorwire_F", 1],
	["Land_LampAirport_F", 5],
	["Land_LampHarbour_F", 1],
	["Land_LampShabby_F", 1],
	["Land_LampSolar_F", 1],
	["Land_LampStreet_F", 1],
	["Campfire_burning_F", 1]
];

//--- Base/Base_East.sqf: STRUCTURE prices (9) ---
CTI_PRICES_STRUCTURES_EAST = createHashMapFromArray [
	["Land_Cargo_House_V1_F", 1000],
	["Land_i_Garage_V1_F", 2000],
	["Land_i_House_Small_03_V1_F", 3000],
	["Land_Cargo_HQ_V1_F", 3500],
	["Land_Radar_Small_F", 8000],
	["Land_TBox_F", 500],
	["Land_FuelStation_Build_F", 600],
	["Land_Lighthouse_small_F", 1500],
	["Land_TTowerBig_1_F", 8000]
];

//--- Base/Base_East.sqf: STRUCTURE build times (9) ---
CTI_PRICES_STRUCT_TIMES_EAST = createHashMapFromArray [
	["Land_Cargo_House_V1_F", 60],
	["Land_i_Garage_V1_F", 80],
	["Land_i_House_Small_03_V1_F", 90],
	["Land_Cargo_HQ_V1_F", 120],
	["Land_Radar_Small_F", 140],
	["Land_TBox_F", 40],
	["Land_FuelStation_Build_F", 35],
	["Land_Lighthouse_small_F", 35],
	["Land_TTowerBig_1_F", 120]
];

//--- Base/Base_East.sqf: DEFENSE prices (65) ---
CTI_PRICES_DEFENSES_EAST = createHashMapFromArray [
	["O_G_HMG_02_F", 150],
	["O_G_HMG_02_high_F", 150],
	["O_HMG_01_High_F", 200],
	["O_GMG_01_high_F", 350],
	["O_static_AT_F", 900],
	["O_static_AA_F", 800],
	["O_Mortar_01_F", 10000],
	["B_AAA_System_01_F", 25000],
	["B_SAM_System_01_F", 40000],
	["O_Radar_System_02_F", 20000],
	["O_SAM_System_04_F", 50000],
	["Land_LampHalogen_F", 5],
	["O_supplyCrate_F", 7],
	["Land_BagBunker_Small_F", 15],
	["Land_Dome_Small_F", 1500],
	["Land_Dome_Big_F", 6000],
	["Land_Cargo_Patrol_V1_F", 50],
	["Land_Shed_Big_F", 40],
	["Land_Cargo_Tower_V1_F", 5000],
	["Land_Mil_WiredFence_F", 5],
	["Land_Mil_WallBig_4m_F", 20],
	["Land_CncWall4_F", 20],
	["Land_HBarrier_5_F", 20],
	["Land_HBarrierBig_F", 20],
	["Land_HBarrierWall6_F", 40],
	["Land_HBarrierWall_corridor_F", 20],
	["Land_HBarrierTower_F", 40],
	["Land_CncBarrier_stripes_F", 15],
	["Land_Medevac_house_V1_F", 3000],
	["CamoNet_OPFOR_F", 50],
	["CamoNet_OPFOR_open_F", 50],
	["CamoNet_OPFOR_big_F", 50],
	["Land_DragonsTeeth_01_1x1_new_F", 40],
	["Land_CzechHedgehog_01_new_F", 40],
	["Land_ConcreteHedgehog_01_F", 40],
	["Flag_CSAT_F", 50],
	["Land_BagFence_Long_F", 5],
	["Land_BagFence_Short_F", 5],
	["Land_BagFence_Round_F", 5],
	["Land_Shed_Small_F", 200],
	["Land_Mil_WiredFence_Gate_F", 5],
	["Land_HelipadSquare_F", 10],
	["Land_Obstacle_Ramp_F", 1],
	["MapBoard_altis_F", 1],
	["Land_i_Shed_Ind_F", 2000],
	["Land_TentHangar_V1_F", 1000],
	["Land_Hangar_F", 2500],
	["Land_LightHouse_F", 2000],
	["Land_i_Barracks_V2_F", 3000],
	["Land_Flush_Light_green_F", 1],
	["Land_Flush_Light_red_F", 1],
	["Land_Flush_Light_yellow_F", 1],
	["Land_runway_edgelight_blue_F", 1],
	["Land_runway_edgelight", 1],
	["Land_Runway_PAPI", 1],
	["Land_Runway_PAPI_2", 1],
	["Land_Runway_PAPI_3", 1],
	["Land_Runway_PAPI_4", 1],
	["Land_Razorwire_F", 1],
	["Land_LampAirport_F", 5],
	["Land_LampHarbour_F", 1],
	["Land_LampShabby_F", 1],
	["Land_LampSolar_F", 1],
	["Land_LampStreet_F", 1],
	["Campfire_burning_F", 1]
];
